#!/bin/bash

feh --bg-scale ~/Downloads/wp.png
setxkbmap en -model thinkpad
dwmblocks &

while true; do
    # Log stderr to a file
    dwm 2> ~/.dwm.log
    # No error logging
    # dwm >/dev/null 2>&1
  done
